version: '3.8'

networks:
  wordcloud-network:

services:
  database:
    image: 'postgres:16'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=wordcloud_db'
      - 'POSTGRES_PASSWORD=postgres'
    networks:
      - wordcloud-network

  rabbitmq:
    image: 'rabbitmq:3.12.12-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - 'RABBITMQ_DEFAULT_USER=guest'
      - 'RABBITMQ_DEFAULT_PASS=guest'
    networks:
      - wordcloud-network

  worker:
    image: 'wordcloud-worker:1.0.5'
    ports:
      - '8081:8081'
    depends_on:
      - rabbitmq
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    networks:
      - wordcloud-network

  core:
    image: 'wordcloud-core:1.0.3'
    ports:
      - '8080:8080'
    depends_on:
      - database
      - worker
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    networks:
      - wordcloud-network

  front:
    image: 'wordcloud-front:1.0.11'
    ports:
      - '3000:80'
    depends_on:
      - core
    networks:
      - wordcloud-network