services:
  database:
    image: 'postgres:16'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=wordcloud_db'
      - 'POSTGRES_PASSWORD=postgres'

  rabbitmq:
    image: 'rabbitmq:3.12.12-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - 'RABBITMQ_DEFAULT_USER=guest'
      - 'RABBITMQ_DEFAULT_PASS=guest'