services:
  database:
    image: 'postgres:16'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=wordcloud_db'
      - 'POSTGRES_PASSWORD=postgres'

  rabbitmq:
    image: 'rabbitmq:3.12.12-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - 'RABBITMQ_DEFAULT_USER=guest'
      - 'RABBITMQ_DEFAULT_PASS=guest'

#  wordcloud-app:
#    image: 'core:0.0.1-SNAPSHOT'
#    ports:
#      - '8080:8080'
#    depends_on:
#      - database
#      - rabbitmq
#    environment:
#      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/wordcloud_db'
#      - 'SPRING_DATASOURCE_USERNAME=postgres'
#      - 'SPRING_DATASOURCE_PASSWORD=postgres'
#      - 'SPRING_FLYWAY_URL=jdbc:postgresql://database:5432/wordcloud_db'
#      - 'SPRING_FLYWAY_PASSWORD=postgres'
#      - 'SPRING_FLYWAY_USER=postgres'
#      - 'RABBITMQ_HOST=rabbitmq'
#      - 'RABBITMQ_PORT=5672'
#      - 'RABBITMQ_USERNAME=guest'
#      - 'RABBITMQ_PASSWORD=guest'